version: '3.9'

services:
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=business_hero

    volumes:
      - ./data/db:/var/lib/postgresql/data/

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5

  backend:
    build:
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=business_hero

    ports:
      - '8000:8000'

    volumes:
      - ./:/app/

    depends_on:
      db:
        condition: service_healthy

  migrate:
    build: .
    command: python manage.py migrate
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=business_hero
